---
name: Code Review - Linting & Link Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run github/super-linter
        uses: github/super-linter@v7
        env:
          # Lint all code - disabled in as part of #262
          VALIDATE_ALL_CODEBASE: false
          # Need to define main branch as default is set to master in super-linter
          DEFAULT_BRANCH: main
          # Enable setting the status of each individual linter run in the Checks section of a pull request
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The following linter types will be enabled:
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_POWERSHELL: true
          VALIDATE_YAML: true
          VALIDATE_EDITORCONFIG: true
          #Â Added exclusion in workflow for generated documentation. PR #304
          FILTER_REGEX_EXCLUDE: (.*generateddocs/.*.bicep.md$|.*.tests.ps1)

  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Check links in markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          config-file: ".github/actions-config/mlc_config.json"
          use-verbose-mode: "yes"
          use-quiet-mode: "yes"
